from app.routers.admin import router as admin_router
from app.routers.admin_extras import router as admin_extras_router
from app.routers.auth import router as auth_router
from app.routers.availability import router as availability_router
from app.routers.cart import router as cart_router
from app.routers.earnings import router as earnings_router
from app.routers.payments import router as payments_router
from app.routers.products import router as products_router
from app.routers.reports import router as reports_router
from app.routers.reviews import router as reviews_router
from app.routers.service import router as service_router
from app.routers.sessions import router as sessions_router
from app.routers.settings import router as settings_router
from app.routers.therapists import router as therapists_router
from app.routers.uploads import router as uploads_router
from app.routers.patients import router as patients_router
from app.routers.clinics import router as clinics_router
