from app.config import settings
from app.database import db, get_db
from app.deps import get_admin_user, get_current_user

from app.models import (
    CartItemCreate,
    CartItemResponse,
    CartItemUpdate,
    CartResponse,
    LoginRequest,
    PaymentCreate,
    PaymentListResponse,
    PaymentResponse,
    ProductCreate,
    ProductListResponse,
    ProductResponse,
    ProductUpdate,
    ReportCreate,
    ReportResponse,
    ReportUpdate,
    SessionCreate,
    SessionListResponse,
    SessionResponse,
    SessionUpdate,
    SignupRequest,
    TherapistCreate,
    TherapistListResponse,
    TherapistResponse,
    TherapistUpdate,
    TokenResponse,
    UserResponse,
)

from app.services import (
    add_to_cart,
    authenticate_user,
    clear_cart,
    create_access_token,
    create_payment,
    create_product,
    create_report,
    create_session,
    create_therapist,
    create_user,
    delete_product,
    delete_report,
    delete_session,
    delete_therapist,
    get_all_payments,
    get_all_sessions,
    get_cart,
    get_payment,
    get_payments_for_user,
    get_product,
    get_products,
    get_report,
    get_reports_for_patient,
    get_session,
    get_sessions_for_patient,
    get_sessions_for_therapist,
    get_therapist,
    get_therapist_by_user,
    get_therapists,
    hash_password,
    remove_cart_item,
    update_cart_item,
    update_payment,
    update_product,
    update_report,
    update_session,
    update_therapist,
    verify_password,
)

from app.routers import (
    admin_router,
    auth_router,
    cart_router,
    payments_router,
    products_router,
    reports_router,
    sessions_router,
    therapists_router,
)

from app.main import app
