from app.config import settings
from app.database import db, get_db
from app.deps import PaginationParams, get_admin_user, get_current_user, get_or_404, pagination_params

from app.models import (
    CartItemCreate,
    CartItemResponse,
    CartItemUpdate,
    CartResponse,
    ChangePasswordRequest,
    LoginRequest,
    NextSessionInfo,
    PatientDashboardResponse,
    PaymentCreate,
    PaymentListResponse,
    PaymentResponse,
    ProductCreate,
    ProductListResponse,
    ProductResponse,
    ProductUpdate,
    ReferralResponse,
    ReportCreate,
    ReportResponse,
    ReportUpdate,
    ReviewCreate,
    ReviewListResponse,
    ReviewResponse,
    SessionCreate,
    SessionListResponse,
    SessionResponse,
    SessionUpdate,
    SignupRequest,
    TherapistCreate,
    TherapistDashboardResponse,
    TherapistListResponse,
    TherapistResponse,
    TherapistToRate,
    TherapistUpdate,
    TokenResponse,
    UserResponse,
    UserUpdate,
)

from app.services import (
    add_to_cart,
    authenticate_user,
    clear_cart,
    create_access_token,
    create_payment,
    create_product,
    create_report,
    create_review,
    create_session,
    create_therapist,
    create_user,
    delete_product,
    delete_report,
    delete_session,
    delete_therapist,
    generate_referral_code,
    get_all_payments,
    get_all_sessions,
    get_cart,
    get_completed_sessions_without_review,
    get_my_patients,
    get_patient_dashboard,
    get_patient_referral,
    get_payment,
    get_payments_for_user,
    get_product,
    get_products,
    get_report,
    get_reports_for_patient,
    get_review_by_patient_and_therapist,
    get_review_by_session,
    get_reviews_for_patient,
    get_session,
    get_sessions_for_patient,
    get_sessions_for_therapist,
    get_therapist,
    get_therapist_by_user,
    get_therapist_dashboard,
    get_therapists,
    hash_password,
    remove_cart_item,
    update_cart_item,
    update_payment,
    update_product,
    update_report,
    update_session,
    update_therapist,
    update_user,
    verify_password,
)

from app.routers import (
    admin_router,
    auth_router,
    cart_router,
    patients_router,
    payments_router,
    products_router,
    reports_router,
    reviews_router,
    sessions_router,
    therapists_router,
)


